server:
  port: 5656

spring:
  redis:
    host: localhost
#    password:
    port: 36379
    lettuce:
      pool:
        max-active: 8 # 最大连接数
        max-idle: 8 # 最大空闲连接
        min-idle: 0 #最小空闲连接
        max-wait: 100ms # 连接等待时间
